# Generated by Django 5.2.4 on 2025-08-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_registration_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
