# Generated by Django 5.2.4 on 2025-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
