# Generated by Django 5.2.4 on 2025-08-05 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentanswerdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'Student'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
