# Generated by Django 5.2.4 on 2025-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
    ]
