# Generated by Django 5.2.4 on 2025-08-05 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_course_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswerdocument',
            unique_together={('exam', 'student')},
        ),
    ]
