# Generated by Django 5.2.4 on 2025-08-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
