# Generated by Django 5.2.4 on 2025-08-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
