# Generated by Django 5.2.4 on 2025-08-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_studentanswer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
