# Generated by Django 5.2.4 on 2025-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_studentanswer_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswerdocument',
            name='total_marks',
            field=models.FloatField(default=0.0),
        ),
    ]
